name: ColonyModerationSystem
version: 2.0
author: ACrispyCookie
main: net.colonymc.colonymoderationsystem.spigot.Main
depend: [ColonyAPI, ColonySpigotAPI]
commands: 
  queue:
    description: Command used to get in queue.
    aliases: [play]
  leavequeue:
    description: Command used to leave the queue.
    aliases: [leaveplay]
  